import { ManualGame } from '@/types';

export const devGames: ManualGame[] = [
  {
    id: '1',
    title: 'Cyberpunk 2077',
    platform: 'PC',
    status: 'Finished',
    score: '9',
    notes: 'Incredible redemption story. The city feels so alive.',
  },
  {
    id: '2',
    title: 'Baldur\'s Gate 3',
    platform: 'PC',
    status: 'Finished',
    score: '10',
    notes: 'Best RPG ever made. My choices actually mattered.',
  },
  {
    id: '3',
    title: 'The Legend of Zelda: Tears of the Kingdom',
    platform: 'Switch',
    status: 'Finished',
    score: '10',
    notes: 'The building mechanics are a game-changer.',
  },
  {
    id: '4',
    title: 'Red Dead Redemption 2',
    platform: 'PlayStation',
    status: 'Finished',
    score: '10',
    notes: 'A masterpiece of storytelling and world-building.',
  },
  {
    id: '5',
    title: 'Starfield',
    platform: 'Xbox',
    status: 'Dropped',
    score: '6',
    notes: 'Felt a bit empty. The exploration wasn\'t rewarding.',
  },
  {
    id: '6',
    title: 'Elden Ring',
    platform: 'PC',
    status: 'Finished',
    score: '9',
    notes: 'Brutal but fair. The sense of discovery is unmatched.',
  },
  {
    id: '7',
    title: 'Hades',
    platform: 'Switch',
    status: 'Played It',
    score: '9',
    notes: 'Amazing voice acting and a super addictive gameplay loop.',
  },
  {
    id: '8',
    title: 'Stardew Valley',
    platform: 'PC',
    status: 'Played It',
    score: '8',
    notes: 'The perfect game to relax with after a long day.',
  },
  {
    id: '9',
    title: 'Dave the Diver',
    platform: 'PC',
    status: 'Finished',
    score: '9',
    notes: 'What a surprise hit. So much to do, and all of it is fun.',
  },
  {
    id: '10',
    title: 'Factorio',
    platform: 'PC',
    status: 'Played It',
    score: '10',
    notes: 'The factory must grow. Cracktorio is real.',
  },
];
